/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:1597713a-ce6c-40be-a2cc-3a50b026198d",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_tkOAWO7CO",
    "aws_user_pools_web_client_id": "53p3d28vrldf5efup7imhigec0",
    "oauth": {}
};


export default awsmobile;
